django01/produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produtos/', views.lista_produtos, name='lista_produtos'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto')
]

django01/projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from projeto import views, settings

urlpatterns = [
    path('', views.index),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('autenticacao/', include('autenticacao.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django01/produto/models.py
from django.db import models
from django.urls import reverse

from categoria.models import Category


class Product(models.Model):

    name = models.CharField(max_length=70, db_index=True, unique=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    branch = models.CharField(max_length=70, default='')
    slug = models.SlugField(max_length=70)
    image = models.ImageField(upload_to='images/')
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    available = models.BooleanField(default=False)

    class Meta:
        db_table="product"
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_availabe(self):
        if self.available:
            return 'Sim'
        else:
            return 'Não'

    def get_absolute_url(self):
        return reverse('carrinho:exibe_produto', args=[self.id, self.slug])

django01/produto/forms/productForm.py
from django import forms
from django.core.validators import RegexValidator

from categoria.models import Category
from produto.models import Product
from projeto import settings




class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'category', 'branch', 'price', 'quantity', 'image',  'available')
        localized_fields = ('price',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].error_messages={'required': 'Campo obrigatório.',
                                            'unique': 'Nome de produto duplicado.'}
        self.fields['name'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['category'].error_messages={'required': 'Campo obrigatório'}
        self.fields['category'].queryset=Category.objects.all().order_by('name')
        self.fields['category'].empty_label='--- Selecione uma categoria ---'
        self.fields['category'].widget.attrs.update({'class': 'form-control form-control-sm'})


        self.fields['price'].min_value=0
        self.fields['price'].error_messages={'required': 'Campo obrigatório.',
                                             'invalid': 'Valor inválido.',
                                             'max_digits': 'Mais de 5 dígitos no total.',
                                             'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                             'max_whole_digits': 'Mais de 3 dígitos inteiros.'}
        self.fields['price'].widget.attrs.update({
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['quantity'].min_value=0
        self.fields['quantity'].error_messages={
            'required': 'Campo obrigatório',
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['quantity'].widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['image'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['image'].widget.attrs.update({'class': 'btn btn-outline-secondary btn-sm'})
        self.fields['image'].required = True

django01/produto/views.py
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.text import slugify

from produto.models import Product
from produto.forms.productForm import ProductForm


@user_passes_test(lambda u: u.is_staff)
def lista_produtos(request):
    products = Product.objects.all().order_by('name')
    return render(request, 'product/products.html', {'products': products})


@user_passes_test(lambda u: u.is_staff)
def cadastra_produto(request):

    if request.POST:
        produto_id = request.session.get('produto_id')
        print('produto_id na sessão = ' + str(produto_id))
        if produto_id:
            produto = get_object_or_404(Product, pk=produto_id)
            produto_form = ProductForm(request.POST, request.FILES, instance=produto)
        else:
            produto_form = ProductForm(request.POST, request.FILES)

        if produto_form.is_valid():
            produto = produto_form.save(commit=False)
            produto.slug = slugify(produto.name)
            produto.save()
            if produto_id:
                messages.add_message(request, messages.INFO, 'Produto alterado com sucesso!')
                del request.session['produto_id']
            else:
                messages.add_message(request, messages.INFO, 'Produto cadastrado com sucesso!')

            return redirect('produto:exibe_produto', id=produto.id)
    else:
        try:
            del request.session['produto_id']
        except KeyError:
            pass
        produto_form = ProductForm()

    return render(request, 'product/cadastra_produto.html', {'form': produto_form})

@user_passes_test(lambda u: u.is_staff)
def exibe_produto(request, id):
    produto = get_object_or_404(Product, pk=id)
    request.session['produto_id_del'] = id
    return render(request, 'product/exibe_produto.html', {'product': produto})

@user_passes_test(lambda u: u.is_staff)
def edita_produto(request, id):
    produto = get_object_or_404(Product, pk=id)
    produto_form = ProductForm(instance=produto)
    request.session['produto_id'] = id
    return render(request, 'product/cadastra_produto.html', {'form': produto_form})

@user_passes_test(lambda u: u.is_staff)
def remove_produto(request):
    produto_id = request.session.get('produto_id_del')
    produto = get_object_or_404(Product, id=produto_id)
    produto.imagem.delete()
    produto.delete()
    del request.session['produto_id_del']
    messages.add_message(request, messages.INFO, 'Produto removido com sucesso.')
    return render(request, 'product/exibe_produto.html', {'product': produto})

django01/produto/templates/product/cadastra_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="{% url 'produto:cadastra_produto' %}" method="POST" class="pb-4"
         enctype="multipart/form-data" novalidate style="min-height: 323px">
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.name }}
                  {# <input type="text" name="nome" maxlength="100" required="" id="id_nome"> #}
                  {% if form.name.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.name.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_descricao" class="col-xl-3 font-weight-bold">Marca</label>
               <div class="col-xl-9">
                  {{ form.branch }}
                  {# <input type="text" name="descricao" maxlength="100" required="" id="id_descricao"> #}
                  {% if form.branch.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.branch.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.category }}
                  {% comment %}
                     <select name="categoria" required="" id="id_categoria">
                        <option value="" selected="">---------</option>
                        <option value="1">Feminino</option>
                        <option value="2">Masculino</option>
                        <option value="3">Nacional</option>
                        <option value="3">Internacional</option>
                     </select>
                  {% endcomment %}
                  {% if form.category.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.category.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>

      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_preco" class="col-xl-2 font-weight-bold">Preço</label>
               <div class="col-xl-10">
                  {{ form.price }}
                  {# <input type="number" name="preco" value="0" step="0.01" required="" id="id_preco"> #}
                  {% if form.price.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.price.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_qtd_estoque" class="col-xl-3 font-weight-bold">Estoque</label>
               <div class="col-xl-9">
                  {{ form.quantity }}
                  {# <input type="number" name="qtd_estoque" value="0" required="" id="id_qtd_estoque"> #}
                  {% if form.quantity.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.quantity.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_imagem" class="col-xl-2 font-weight-bold">Imagem</label>
               <div class="col-xl-10">
                  {{ form.image }}
                  {# <input type="text" name="imagem" maxlength="50" id="id_imagem"> #}
                  {% if form.image.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.image.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <div class="offset-xl-3 col-xl-9">
                  <div class="form-check pl-0 mt-xl-0 mt-2">
                     {{ form.available }}
                     {# <input type="checkbox" name="disponivel" id="id_disponivel"> #}
                     <label for="id_disponivel" class="form-check-label">Disponível?</label>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  {% csrf_token %}
                  <button id="botao" type="submit" class="btn btn-primary">
                     {% if 'produto_id' in request.session %}
                        <img src="{% static 'images/skin/database_edit.png' %}"> Alterar
                     {% else %}
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                     {% endif %}
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>

{% endblock %}

{% block domready %}


{% endblock %}

django01/produto/templates/product/exibe_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   {% if messages %}
      <div class="mb-3">
         {% for message in messages %}
            <ul class="list-group rounded">
               <li style="padding-top: 7px; padding-bottom: 7px"
                   class="list-group-item list-group-item-info">
                  {{ message }}
               </li>
            </ul>
         {% endfor %}
      </div>
   {% endif %}

   <div class="row mb-3">
         <div class="col-lg-3 col-md-4">
            {% if product.image %}
               <img class="mr-3" style="width: 210px"
                    src="{{product.image.url}}" alt="{{ product.name }}">
            {% else %}
               <div class="text-md-center mb-md-0 mb-2">
                  Imagem não disponível
               </div>
            {% endif %}
         </div>
      <div class="col-lg-9 col-md-8">
         <div class="row">
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Categoria</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.category }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Nome</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.name }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Marca</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.branch }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Preço</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.price }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Estoque</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.quantity }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Disponível</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ product.available }}</div>
         </div>
      </div>
   </div>

   {% if product.id %}
         <div class="form-group row">
            <div class="col-12">
               <div class="form-inline">
                  <a href="{% url 'produto:edita_produto' product.id %}" class="btn btn-primary mr-3">
                     <img src="{% static 'images/skin/database_edit.png' %}" /> Editar
                  </a>

                  <form action="{% url 'produto:remove_produto' %}" method="POST">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">
                        <img src="{% static 'images/skin/database_delete.png' %}"> Remover
                     </button>
                  </form>
               </div>
            </div>
         </div>
   {% endif %}

{% endblock %}

django01/produto/templates/product/products.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Pesquisa de Produtos
{% endblock %}

{% block corpo %}

   <h5 class="mb-3">Lista de Produtos</h5>
   <table style='width:100%'
          class='table table-striped table-sm table-bordered table-responsive mb-4'>
      <thead>
         <tr>
            <th class='text-center'>Imagem</th>
            <th class='text-center'>Categoria</th>
            <th class='text-center'>Nome</th>
            <th class="text-center">Disponível</th>
            <th class='text-center'>Marca</th>
            <th class="text-center">Quantidade</th>
            <th class="text-center">Preço Unitário</th>
         </tr>
      </thead>
      <tbody>
         {% for product in products %}
         <tr>
               <td width="10%" class="text-center align-middle">
                  <img style="width:80px"
                             src="{{ product.image.url }}" alt="{{ product.name }}">
               </td>
               <td width="10%" class="text-center align-middle">
                  {{ product.category }}
               </td>
               <td width="35%" class="text-center align-middle">
                   <a href="{% url 'produto:exibe_produto' product.id %}">
                        {{ product.name }}
                   </a>
               </td>
               <td width="10%" class="text-center align-middle">
                  {{ product.get_availabe }}
               </td>
               <td width="15%" class="text-center align-middle">
                  {{ product.branch }}
               </td>
               <td width="10%" class="text-right align-middle pr-3">
                  {{ product.quantity }}
               </td>
               <td width="15%" class="text-right align-middle pr-3">
                  R$ {{ product.price }}
               </td>
            </tr>
         {% endfor %}
      </tbody>
   </table>

{% endblock %}

django01/produto/templates/product/products2.html
{% extends "base.html" %}

{% load static %}

{%block titulo%}
    Produtos
{%enblock%}

{%block corpo%}